[workspace]
members = ["crates/player", "crates/player_core", "crates/ui"]
default-members = ["crates/player"]
resolver = "2"

[workspace.dependencies]
player_core = { path = "crates/player_core" }
ui = { path = "crates/ui" }

gpui = { git = "https://github.com/gpui-ce/gpui-ce" }
